spring:
  profiles:
    active: ${ENV:prod}
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DATABASE_NAME:pingtai}?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
###############################---management---##############################
management:
  endpoints:
    web:
      exposure:
        include: '*'
###############################---eureka---##############################
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost:8761}/eureka/
  instance:
    prefer-ip-address: true
###############################---jwt---##############################
jwt:
  # 加密秘钥
  secret: f4e2e5203434xx1WET12^%3^(WE45
  # token有效时长，7天，单位秒
  expire: 604800
  header: token
###############################---log---##############################
logging:
  file: ./logback.log
###############################---网关超时设置---##############################
ribbon:
  eureka:
    enable: true
  ReadTimeout: 300  #请求处理的超时时间
  ConnectTimeout: 500  #请求连接的超时时间
  SocketTimeout: 500
  #OkToRetryOnAllOperations: true  #对所有请求都开启重试
  MaxAutoRetries: 1  #对当前服务的重试次数（如果404，则再重试MaxAutoRetries次，如果还是404，则切换到其他服务)
  MaxAutoRetriesNextServer: 1  #切换服务的次数，只切换一次服务，不行就拉倒
  retryableStatusCodes: 404,502,500,408
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
###############################---前缀---##############################
zuul:
  ribbon:
    eager-load:
      enabled: true
  prefix: /api
  retryable: true